FROM node:14.16.0-alpine3.13



RUN addgroup app && adduser -S -G app app

RUN mkdir /app && chown app:app /app

USER app

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

FROM nginx:1.12-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80 

#CMD ["npm", "start"]

ENTRYPOINT [ "nginx","-g", "daemon off;" ]